services:
  - type: web
    name: germination-api
    env: python
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
